import api from '@/lib/api';
import type {
    SuratKeluar,
    CreateSuratKeluarPayload,
    UpdateSuratKeluarPayload,
    ListSuratKeluarParams
} from '@/features/surat-keluar/types';

export const suratKeluarService = {
    /**
     * List all surat keluar with optional filters
     */
    async getAll(params?: ListSuratKeluarParams): Promise<SuratKeluar[]> {
        const response = await api.get<SuratKeluar[]>('/surat-keluar', { params });
        return response.data;
    },

    /**
     * Get surat keluar by ID
     */
    async getById(id: number): Promise<SuratKeluar> {
        const response = await api.get<SuratKeluar>(`/surat-keluar/${id}`);
        return response.data;
    },

    /**
     * Create a new surat keluar with file upload (multipart/form-data)
     * Note: nomor_surat_keluar is auto-generated by the backend
     */
    async create(payload: CreateSuratKeluarPayload): Promise<SuratKeluar> {
        const formData = new FormData();
        formData.append('file', payload.file);
        formData.append('tanggal_surat', payload.tanggal_surat);
        formData.append('penerima', payload.penerima);
        formData.append('perihal', payload.perihal);
        formData.append('kategori_id', payload.kategori_id.toString());
        if (payload.status) formData.append('status', payload.status);
        if (payload.priority) formData.append('priority', payload.priority);

        const response = await api.post<SuratKeluar>('/surat-keluar', formData, {
            headers: { 'Content-Type': 'multipart/form-data' }
        });
        return response.data;
    },

    /**
     * Update surat keluar metadata
     */
    async update(id: number, data: UpdateSuratKeluarPayload): Promise<SuratKeluar> {
        const response = await api.put<SuratKeluar>(`/surat-keluar/${id}`, data);
        return response.data;
    },

    /**
     * Delete surat keluar (returns 204 No Content)
     */
    async delete(id: number): Promise<void> {
        await api.delete(`/surat-keluar/${id}`);
    },

    /**
     * Download associated file
     * Returns a Blob URL for the file
     */
    async downloadFile(id: number): Promise<string> {
        const response = await api.get(`/surat-keluar/${id}/file`, {
            responseType: 'blob'
        });
        return URL.createObjectURL(response.data);
    }
};
