"""add audit_logs table

Revision ID: 650bde821c78
Revises: b80a5d4d3255
Create Date: 2026-02-11 11:03:06.795857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650bde821c78'
down_revision = 'b80a5d4d3255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifikasi',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.Enum('SURAT_MASUK', 'SURAT_KELUAR', 'DISPOSISI', 'DEADLINE', 'STATUS_UPDATE', 'SYSTEM', name='tipenotifikasi'), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('surat_masuk_id', sa.Integer(), nullable=True),
    sa.Column('surat_keluar_id', sa.Integer(), nullable=True),
    sa.Column('disposisi_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disposisi_id'], ['disposisi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surat_keluar_id'], ['surat_keluar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surat_masuk_id'], ['surat_masuk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifikasi_id'), 'notifikasi', ['id'], unique=False)
    op.create_index(op.f('ix_notifikasi_is_read'), 'notifikasi', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifikasi_tipe'), 'notifikasi', ['tipe'], unique=False)
    op.create_index(op.f('ix_notifikasi_user_id'), 'notifikasi', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifikasi_user_id'), table_name='notifikasi')
    op.drop_index(op.f('ix_notifikasi_tipe'), table_name='notifikasi')
    op.drop_index(op.f('ix_notifikasi_is_read'), table_name='notifikasi')
    op.drop_index(op.f('ix_notifikasi_id'), table_name='notifikasi')
    op.drop_table('notifikasi')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
