"""initial schema

Revision ID: b1a930a69e0b
Revises: 
Create Date: 2026-02-11 10:43:45.497653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a930a69e0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode'),
    sa.UniqueConstraint('nama')
    )
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('surat_keluar',
    sa.Column('nomor_surat_keluar', sa.String(length=100), nullable=False),
    sa.Column('tanggal_surat', sa.Date(), nullable=False),
    sa.Column('penerima', sa.String(length=255), nullable=False),
    sa.Column('tembusan', sa.Text(), nullable=True),
    sa.Column('perihal', sa.String(length=500), nullable=False),
    sa.Column('isi_singkat', sa.Text(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('BARU', 'PROSES', 'SELESAI', 'ARSIP', name='statussurat'), nullable=False),
    sa.Column('priority', sa.Enum('RENDAH', 'SEDANG', 'TINGGI', 'URGENT', name='prioritysurat'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surat_keluar_id'), 'surat_keluar', ['id'], unique=False)
    op.create_index(op.f('ix_surat_keluar_kategori_id'), 'surat_keluar', ['kategori_id'], unique=False)
    op.create_index(op.f('ix_surat_keluar_nomor_surat_keluar'), 'surat_keluar', ['nomor_surat_keluar'], unique=True)
    op.create_index(op.f('ix_surat_keluar_penerima'), 'surat_keluar', ['penerima'], unique=False)
    op.create_index(op.f('ix_surat_keluar_priority'), 'surat_keluar', ['priority'], unique=False)
    op.create_index(op.f('ix_surat_keluar_status'), 'surat_keluar', ['status'], unique=False)
    op.create_index(op.f('ix_surat_keluar_tanggal_surat'), 'surat_keluar', ['tanggal_surat'], unique=False)
    op.create_table('surat_masuk',
    sa.Column('nomor_surat', sa.String(length=100), nullable=False),
    sa.Column('tanggal_surat', sa.Date(), nullable=False),
    sa.Column('tanggal_terima', sa.Date(), nullable=False),
    sa.Column('pengirim', sa.String(length=255), nullable=False),
    sa.Column('perihal', sa.String(length=500), nullable=False),
    sa.Column('isi_singkat', sa.Text(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('BARU', 'PROSES', 'SELESAI', 'ARSIP', name='statussurat'), nullable=False),
    sa.Column('priority', sa.Enum('RENDAH', 'SEDANG', 'TINGGI', 'URGENT', name='prioritysurat'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surat_masuk_id'), 'surat_masuk', ['id'], unique=False)
    op.create_index(op.f('ix_surat_masuk_kategori_id'), 'surat_masuk', ['kategori_id'], unique=False)
    op.create_index(op.f('ix_surat_masuk_nomor_surat'), 'surat_masuk', ['nomor_surat'], unique=False)
    op.create_index(op.f('ix_surat_masuk_pengirim'), 'surat_masuk', ['pengirim'], unique=False)
    op.create_index(op.f('ix_surat_masuk_priority'), 'surat_masuk', ['priority'], unique=False)
    op.create_index(op.f('ix_surat_masuk_status'), 'surat_masuk', ['status'], unique=False)
    op.create_index(op.f('ix_surat_masuk_tanggal_surat'), 'surat_masuk', ['tanggal_surat'], unique=False)
    op.create_index(op.f('ix_surat_masuk_tanggal_terima'), 'surat_masuk', ['tanggal_terima'], unique=False)
    op.create_table('disposisi',
    sa.Column('surat_masuk_id', sa.Integer(), nullable=True),
    sa.Column('surat_keluar_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('instruksi', sa.Text(), nullable=True),
    sa.Column('batas_waktu', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DITINDAKLANJUTI', 'SELESAI', 'DIBATALKAN', name='statusdisposisi'), nullable=False),
    sa.Column('tanggal_selesai', sa.DateTime(), nullable=True),
    sa.Column('keterangan_selesai', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['surat_keluar_id'], ['surat_keluar.id'], ),
    sa.ForeignKeyConstraint(['surat_masuk_id'], ['surat_masuk.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disposisi_from_user_id'), 'disposisi', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_disposisi_id'), 'disposisi', ['id'], unique=False)
    op.create_index(op.f('ix_disposisi_status'), 'disposisi', ['status'], unique=False)
    op.create_index(op.f('ix_disposisi_surat_keluar_id'), 'disposisi', ['surat_keluar_id'], unique=False)
    op.create_index(op.f('ix_disposisi_surat_masuk_id'), 'disposisi', ['surat_masuk_id'], unique=False)
    op.create_index(op.f('ix_disposisi_to_user_id'), 'disposisi', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disposisi_to_user_id'), table_name='disposisi')
    op.drop_index(op.f('ix_disposisi_surat_masuk_id'), table_name='disposisi')
    op.drop_index(op.f('ix_disposisi_surat_keluar_id'), table_name='disposisi')
    op.drop_index(op.f('ix_disposisi_status'), table_name='disposisi')
    op.drop_index(op.f('ix_disposisi_id'), table_name='disposisi')
    op.drop_index(op.f('ix_disposisi_from_user_id'), table_name='disposisi')
    op.drop_table('disposisi')
    op.drop_index(op.f('ix_surat_masuk_tanggal_terima'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_tanggal_surat'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_status'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_priority'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_pengirim'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_nomor_surat'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_kategori_id'), table_name='surat_masuk')
    op.drop_index(op.f('ix_surat_masuk_id'), table_name='surat_masuk')
    op.drop_table('surat_masuk')
    op.drop_index(op.f('ix_surat_keluar_tanggal_surat'), table_name='surat_keluar')
    op.drop_index(op.f('ix_surat_keluar_status'), table_name='surat_keluar')
    op.drop_index(op.f('ix_surat_keluar_priority'), table_name='surat_keluar')
    op.drop_index(op.f('ix_surat_keluar_penerima'), table_name='surat_keluar')
    op.drop_index(op.f('ix_surat_keluar_nomor_surat_keluar'), table_name='surat_keluar')
    op.drop_index(op.f('ix_surat_keluar_kategori_id'), table_name='surat_keluar')
    op.drop_index(op.f('ix_surat_keluar_id'), table_name='surat_keluar')
    op.drop_table('surat_keluar')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
