"""add notifikasi table

Revision ID: b80a5d4d3255
Revises: 675eb89f6144
Create Date: 2026-02-11 10:58:31.981091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80a5d4d3255'
down_revision = '675eb89f6144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
